spring:
  application:
    name: kube-spring
  cloud:
    kubernetes:
      config:
        enabled: true
        name: kube-spring
        namespace: default
        sources:
          - name: kube-spring